//Auto generated by tgf util
//created at 2023-05-29 17:44:43.3071196 +0800 CST m=+0.072946601

package api

import (
	"github.com/thkhxm/tgf/rpc"

	"github.com/thkhxm/tgf/example/login/pb"
)

var loginService = &rpc.Module{Name: "login", Version: "1.0"}

var (
	Login = rpc.ServiceAPI[*pb.LoginReq, *pb.LoginRes]{
		ModuleName: loginService.Name,
		Name:       "Login",
	}
)
