//Auto generated by tgf util
//created at 2023-06-12 17:17:01.9016842 +0800 CST m=+0.028897001

package api

import (
	"github.com/thkhxm/tgf/rpc"

	"github.com/thkhxm/tgf/example/common/pb"
)

var loginService = &rpc.Module{Name: "login", Version: "1.0"}

var (
	Login = rpc.ServiceAPI[*pb.LoginReq, *pb.LoginRes]{
		ModuleName:  loginService.Name,
		Name:        "Login",
		MessageType: loginService.Name + "." + "Login",
	}
)
