//Auto generated by tgf util
//created at 2023-04-19 16:57:07.5260334 +0800 CST m=+0.042018101

package conf

type ErrorCodeConf struct {

	//错误码
	Code int32

	//文字
	Message string

	//描述
	Desc string

	//字段名
	FieldName string
}
